### ISSUE TITLE
Sort order is incorrect

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#98] opened 2020-06-26 16:03 UTC
Can’t tell what sort order it was using.  At the beginning are a lot of minor entries (Variants).  Then it continues with the word I expected to be first.  Some words that should be in the sequence are not there (are they somewhere else?  Didn’t check thoroughly), and others that should be are not.
Ut-hun: https://webonary.work/ut-hun
FWBackup file in https://drive.google.com/drive/folders/1IDVEimJF05igvPLuShvguYeYY1fTzJEf

**Comment by vernastutzman** [comment] 2020-06-26 17:12
https://www.webonary.work/ut-hun/browse/browse-vernacular/?letter=a&key=dud
![SortOrderWebonary-utHun](https://user-images.githubusercontent.com/53490028/85883174-2e738c00-b7a6-11ea-96f6-b85a9b389178.JPG)
<img width="582" alt="SortOrder-FLEx-ut-Hun" src="https://user-images.githubusercontent.com/53490028/85883244-4a772d80-b7a6-11ea-88a4-9ab4ad8da5ca.png">

**Comment by bbryson** [comment] 2020-06-26 18:06
The images Verna uploaded show the same view in both FLEx and Webonary.  Note that in FLEx, there are four homographs of "a" as the first several entries.  In Webonary, there is only one at the beginning.  Note that in Webonary, those four homographs do appear, but only after quite a few entries that all have "{var. of ...}" on them, meaning they are Minor Entries.  Is it possible that the entries from the uploaded file minorentryvariant.xhtml are being shown before the ones from entry.xhtml?  Are they not being integrated and all sorted together?  Just making a wild guess.

**Comment by hanatgit** [comment] 2020-06-27 23:52
Sort order is currently based on the first array element in mainHeadWord only. But in cases of homographs, we should take into consideration the second element mainHeadWord.

**Comment by hanatgit** [comment] 2020-06-28 01:13
Verna and Beth, please see

https://www.webonary.work/test-chung/browse/browse-vernacular-french/?letter=a&key=dud&lang=en

I have made a change to account for homographs, but the order is still different from FLex because we are currently doing accent-insensitive sorting.

**Comment by hanatgit** [comment] 2020-06-30 02:02
Changed default index and sorting to be capital insensitive but diacritic sensitive. This appears to get the sorting order correct. If not, we might have to resort to setting sort order for each entries in FLex and posting it.

**Comment by bbryson** [comment] 2020-06-30 02:32
Han-

I’m glad you have things sorted out for the issues you addressed.  However, when I saw the sorting problem the day that Verna and I tested, I never got far enough to notice caps/no-caps, or diacritics, or homograph numbers, because what I noticed was that the items that are Minor Entries (variants) or Minor Entries (complex forms) were not sorted along with the Main Entries.  (They get uploaded to Webonary in three separate files, so that didn’t surprise me.)  What I saw then showed the Minor Entry Variants for "letter A” all grouped together at the beginning of the A section, and then the Main Entries for "letter A”, before it moved on to “letter B".

1. As I look at the .work site now, and compare with webonary.org, I see that the Main Entries are now first, but I don’t see a Variant in the order that I expect.  I wonder if all Variants are now at the end, or possibly missing altogether?  

2. When I look at any entry that says that it has a variant, and I click on the variant, I should be taken to that Minor Entry (Variant), but instead I am told “No entry”.  

Examples:  

a nas-ye̱ o̱ <https://www.webonary.work/test-chung/gfa005819-b8e3-42e2-bac5-67b8cfcde077?lang=en>, a taan-ye̱ o̱ <https://www.webonary.work/test-chung/g0f2c5b0d-3850-406c-a990-6568f540962d?lang=en>, a tet-ye̱ o̱ <https://www.webonary.work/test-chung/g5de88e0e-dc66-4e7b-9d65-4d00bfebae61?lang=en>, a yoor-ye̱ o̱ <https://www.webonary.work/test-chung/gd73213c5-39d2-412b-8475-6eb22b748664?lang=en>

3. Also, where are you getting the sort order from—are you pulling it from the FLEx project, or just basing it on Unicode?  Some projects may use a standard sort order, but many (80%?) of FLEx projects specify their own sort order.  It appears that this FLEx project specified a different order for grave accent vs. acute than webonary.work.  It is crucial to be able to use the sort order defined by the user in the FLEx project—other projects will have much more significant differences compared to a “Unicode standard sort order”.

4. Also, why does the top of the page say it is for French instead of for the vernacular language?   (Maybe that is “work to be done later”, when you make it possible for the users to configure headers for the pages?)

At least now it does show the name of the language that was uploaded, and the number of entries—that is good!

Attaching a screenshot illustrating some of these issues.  If it does not come through, let me know and I’ll try something else.

-Beth

**Comment by bbryson** [comment] 2020-06-30 02:55
P.S.  I don’t know why the entry (a 1 var. of wan) appears last (on webonary.org) in the sequence of all the entries that consist only of the letter a (with or without a diacritic).

My theory is that there is apparently a space after the “a” in the Lexeme Form field in FLEx, and that is why.  That space would be a mistake in the user data.  If the user were to delete that space, it should have gotten a homograph number somewhere in the set for (a with no diacritic), so that there would be 5 homographs instead of 4.

If you were to delete that extra space in the FLEx project, and even change the homograph number to something like 2,3, or 4, then you would be able to test whether variants can be inter-sorted with main entries.

-Beth

**Comment by bbryson** [comment] 2020-06-30 15:35
Beth,

Thanks for your careful investigation and documentation of everything!

There are multiple issues going on, so let me try to explain step by step.

1. We know that FLex has issues with not sending diacritical markers correctly to the backend. This should be fixed in the next FLex release for testing.

2. The test site I pointed to www.webonary.work/test-chung/ <http://www.webonary.work/test-chung/> was created by me for quick testing. That is why it says "French to English". It is not a copy of ut-hun site. Also, I created this site just to try out if I can solve the sorting problem without any changes in FLex. The data for it was uploaded not using FLex, but using my customer loader that I have control over. The purpose of the test was just to see if I can find a better way to sort in unicode (utf-8) that would match FLex's order. The one downside to this experiment was that my customer loader ignores minor variants. That is why they were missing in my test site.

3. Based on my test, and your review and explanation, and also Jason's reply to me that FLex does more that regular unicode sorting in some cases, I think what I had propose to Jason about changing FLex so that it includes a sort order field for each entry it uploads, is necessary so our cloud backend process would depend on them instead of natural unicode order. I will create an issue and request FLex to make that change.

4. It seems that there might still be a problem handling minor variants. I will create an issue and determine where the root cause might be.

Thank you! This is what testing, especially testing involving real users, is for :-)

Han

**Comment by hanatgit** [comment] 2020-07-01 12:19
Taked to FLex team and determined that FLex will add sortOrder to each entry data when posting to the backend. Changed backend load and browse functions to store sortOrder for each entry and use it as the primary sort field. This produced the following result, which is consistent with FLex (minus minor variants data since I am still using legacy loader until new FLex client is ready).
<img width="506" alt="Screen Shot 2020-07-01 at 7 16 36 AM" src="https://user-images.githubusercontent.com/60716623/86242980-2a12ee80-bb6b-11ea-88ec-9ee20dc6cbfc.png">

**Closed as completed** 2020-07-29 01:07 UTC
Labels: high priority
